#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    component: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      volumes:
      - name: atp-secret
        secret:
          defaultMode: 420
          secretName: atp-secret
      containers:
      - name: catalog
        image: shashioracle/catalog-atpsoda:2.0.0
        volumeMounts:
        - mountPath: /home/opc/Wallet_sockshopdb
          name: atp-secret
          readOnly: true

--

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"catalog","component":"sockshop"},"name":"catalogue","namespace":"sockshop-atpsoda"},"spec":{"ports":[{"name":"http","port":80,"targetPort":7001}],"selector":{"app":"catalog"}}}
  labels:
    app: catalog
    component: sockshop
  name: catalogue
  namespace: sockshop-atpsoda
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7001
  selector:
    app: catalog
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}