apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-route-sockshop-atpsoda
  namespace: sockshop-atpsoda 
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end 
          servicePort: 80
