#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-db
  labels:
    name: shipping-db
    component: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shipping-db
  template:
    metadata:
      labels:
        name: shipping-db
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: shipping-db
        image: mongo:4.2.2
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-db
  labels:
    name: shipping-db
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: shipping-db
