apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-sockshop-${SOCKSHOP_BACKEND}
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      component: sockshop
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - sockshop-${SOCKSHOP_BACKEND}
