#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
kind: Service
apiVersion: v1
metadata:
  name: swagger
  labels:
    app: swagger
spec:
  selector:
    app: swagger
  ports:
    - port: 80
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: swagger
          image: swaggerapi/swagger-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
