#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
kind: Service
apiVersion: v1
metadata:
  name: shipping-http
  labels:
    app: shipping
    component: sockshop
spec:
  selector:
    app: shipping
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Service
apiVersion: v1
metadata:
  name: shipping
  labels:
    app: shipping
    component: sockshop
spec:
  selector:
    app: shipping
  ports:
    - port: 1408
      targetPort: 1408
      name: grpc
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
        version: v1
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: shipping
          image: helidonsockshop/shipping-core:2.0.0
          imagePullPolicy: Always
          env:
            - name: TRACING_HOST
              value: "jaeger-collector"
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
          ports:
            - containerPort: 7001
            - containerPort: 1408
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 400Mi
