#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    component: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      volumes:
      - name: atp-secret
        secret:
          defaultMode: 420
          secretName: atp-secret
      containers:
      - name: payment
        image: shashioracle/payment-atpsoda:2.0.0
        volumeMounts:
        - mountPath: /home/opc/Wallet_sockshopdb
          name: atp-secret
          readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"payment","component":"sockshop"},"name":"payment","namespace":"sockshop-atpsoda"},"spec":{"ports":[{"name":"grpc","port":1408,"targetPort":1408}],"selector":{"app":"payment"}}}
  labels:
    app: payment
    component: sockshop
  name: payment
  namespace: sockshop-atpsoda
spec:
  ports:
  - name: grpc
    port: 1408
    protocol: TCP
    targetPort: 1408
  selector:
    app: payment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
