#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment
  labels:
    component: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    spec:
      volumes:
      - name: atp-secret
        secret:
          defaultMode: 420
          secretName: atp-secret
      containers:
        - name: payment
          image: shashioracle/payment-atpsoda:2.0.0
          volumeMounts:
          - mountPath: /home/opc/Wallet_sockshopdb
            name: atp-secret
            readOnly: true
