#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
kind: Service
apiVersion: v1
metadata:
  name: user  # for compatibility with the existing front-end implementation
  labels:
    app: users
    component: sockshop
spec:
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 7001
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: users
          image: helidonsockshop/users-core:2.0.0
          imagePullPolicy: Always
          env:
            - name: TRACING_HOST
              value: "jaeger-collector"
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
          ports:
            - containerPort: 7001
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 400Mi
