#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    component: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      volumes:
      - name: atp-secret
        secret:
          defaultMode: 420
          secretName: atp-secret
      containers:
      - name: orders
        image: shashioracle/orders-atpsoda:2.0.0
        volumeMounts:
        - mountPath: /home/opc/Wallet_sockshopdb
          name: atp-secret
          readOnly: true
          
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"orders","component":"sockshop"},"name":"orders","namespace":"sockshop-atpsoda"},"spec":{"ports":[{"name":"http","port":80,"targetPort":7001}],"selector":{"app":"orders"}}}
  labels:
    app: orders
    component: sockshop
  name: orders
  namespace: sockshop-atpsoda
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7001
  selector:
    app: orders
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}