#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
  labels:
    name: users-db
    component: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: users-db
  template:
    metadata:
      labels:
        name: users-db
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: users-db
        image: redis:5.0.7
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: users-db
  labels:
    name: users-db
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    name: users-db
