#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - carts/app.yaml
  - catalog/app.yaml
  - orders/app.yaml
  - payment/app.yaml
  - shipping/app.yaml
  - users/app.yaml
